# Generated by Django 6.0 on 2026-01-29 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("card", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cardevent",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="cardimage",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="cardsharetoken",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_tokens",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="cardsnapshot",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="cardsharetoken",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="share_tokens",
                to="card.cardsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="usercollection",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collected_by",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="usercollection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cardevent",
            index=models.Index(
                fields=["card", "created_at"], name="card_events_card_id_957f7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardsharetoken",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["access_key"],
                name="idx_active_share_token",
            ),
        ),
        migrations.AddIndex(
            model_name="usercollection",
            index=models.Index(
                fields=["user", "collected_at"], name="user_collec_user_id_f62f2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercollection",
            constraint=models.UniqueConstraint(
                fields=("user", "card"), name="uq_user_card_collect"
            ),
        ),
    ]
