"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# ruff: noqa: E501
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Sentry: SENTRY_DSN 설정 시에만 초기화 (Render 등 로그 제한 환경에서 500 추적)
_sentry_dsn = os.getenv("SENTRY_DSN", "").strip()
if _sentry_dsn:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=_sentry_dsn,
        integrations=[DjangoIntegration()],
        environment=os.getenv("DJANGO_ENV", "development"),
        traces_sample_rate=0,
        send_default_pii=False,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / "envs" / ".local.env"
# 배포(Render 등)에서는 .local.env 로드하지 않음. DJANGO_ENV=production 설정 시 환경 변수만 사용.
if os.getenv("DJANGO_ENV") != "production" and env_path.exists():
    load_dotenv(dotenv_path=env_path)


def _require_env(key: str, default: str | None = None) -> str:
    v = os.getenv(key, default)
    if not (v and str(v).strip()):
        raise ImproperlyConfigured(f"Required environment variable: {key}")
    return str(v).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _require_env("SECRET_KEY")
# ADMIN_URL: 배포 시 반드시 설정. 로컬/CI에서만 디폴트 허용.
if os.getenv("CI") == "true" or os.getenv("DEBUG", "").lower() == "true":
    ADMIN_URL = _require_env("ADMIN_URL", default="admin-secret-path")
else:
    ADMIN_URL = _require_env("ADMIN_URL")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

_allowed = os.getenv("ALLOWED_HOSTS", "").strip()
_ALLOWED_HOSTS_DEFAULT = ["localhost", "127.0.0.1", "0.0.0.0"]
if not _allowed and not DEBUG:
    raise ImproperlyConfigured("ALLOWED_HOSTS required when DEBUG=False")
ALLOWED_HOSTS: list[str] = (
    [h.strip() for h in _allowed.split(",") if h.strip()]
    if _allowed
    else _ALLOWED_HOSTS_DEFAULT
)

# CORS: Vercel 프론트 + 로컬 개발용
CORS_ALLOWED_ORIGINS = [
    "https://business-card-frontend-cdavb159p-lukascruises-projects.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Vercel 배포 URL (커밋/수정할 때마다 바뀌는 주소 허용)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://business-card-frontend(-[a-z0-9-]+)*\.vercel\.app$",
]

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "django_app.user",
    "django_app.card",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Render 등에서 DATABASE_URL 주입 시 사용. 없으면 POSTGRES_* 개별 변수 사용.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=os.getenv("DJANGO_ENV") == "production",
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _require_env("POSTGRES_DB"),
            "USER": _require_env("POSTGRES_USER"),
            "PASSWORD": _require_env("POSTGRES_PASSWORD"),
            "HOST": _require_env("POSTGRES_HOST"),
            "PORT": _require_env("POSTGRES_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = "user.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.services.drf_exception_handler.custom_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Business Card API",
    "DESCRIPTION": "MVP 명함 서비스 API",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


R2_ACCOUNT_ID = _require_env("R2_ACCOUNT_ID")
R2_ACCESS_KEY_ID = _require_env("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = _require_env("R2_SECRET_ACCESS_KEY")
R2_BUCKET_NAME = _require_env("R2_BUCKET_NAME")
CDN_BASE_URL = _require_env("CDN_BASE_URL")
